import waflib.Context

def build(ctx):

    libntp_source = [
        "assert.c",
        "authkeys.c",
        "authreadkeys.c",
        "clocktime.c",
        "decodenetnum.c",
        "dolfptoa.c",
        "getopt.c",
        "initnetwork.c",
        "isc_error.c",
        "isc_interfaceiter.c",
        "isc_net.c",
        "macencrypt.c",
        "netof.c",
        "ntp_endian.c",
        "numtoa.c",
        "refidsmear.c",
        "socket.c",
        "socktoa.c",
        "ssl_init.c",
        "syssignal.c",
    ]

    libntp_source_sharable = [
        "clockwork.c",
        "emalloc.c",
        "hextolfp.c",
        "lib_strbuf.c",
        "msyslog.c",
        "ntp_calendar.c",
        "ntp_random.c",
        "prettydate.c",
        "statestr.c",
        "systime.c",
        "timespecops.c",
    ]

    if not ctx.env.HAVE_STRLCAT or not ctx.env.HAVE_STRLCPY:
        libntp_source_sharable += ["strl_obsd.c"]

    includes = [waflib.Context.out_dir, "%s/include" % waflib.Context.top_dir]

    # C library
    ctx.stlib(
        includes=includes + ["../build", "../include"],
        source=libntp_source + libntp_source_sharable,
        target="ntp",
        use="SSL CRYPTO",
    )

    # Loadable Python extension
    ctx(
        features="c cshlib pyext",
        install_path='${PYTHONARCHDIR}/ntp',
        includes=includes,
        source=["pymodule.c"] + libntp_source_sharable,
        target="../pylib/ntpc",  # Put the output in the pylib directory
        use="M RT CRYPTO",
    )
