import waflib.Context

def build(ctx):
    # libaes_siv has warnings when built with -Wshadow, so make sure to use
    # -Wno-shadow
    ctx.env.CFLAGS_cstlib = ['-Wno-shadow']

    ctx(
        target="aes_siv",
        features="c" ,
        source="aes_siv.c",
        use="CRYPTO",
        includes=[waflib.Context.out_dir, "%s/include" % waflib.Context.top_dir],
    )
